export enum AppPages {
  ACTIVATE = '/activate-page',
  ADD_POST_PAGE = '/add-post-page',
  ALL_POST = '/all-post-page',
  INFORMATION = '/information-page',
  LOGIN_CONFIRMATION = '/login-confirmation-page',
  LOGIN_FORM = '/login-page',
  MAIN = '/first-page',
  MY_POSTS_PAGE = '/my-post-page',
  POST_PAGE = '/post-page',
  REGISTRATION_CONFIRMATION = '/registration-confirmation-page',
  REGISTRATION_FORM = '/registration-page',
  SELECTED_POST = '/selected-post-page',
  HOME = '/home',
}
